# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  # ---------------------------------------------------
  # JOB 1: Build & Test
  # ---------------------------------------------------
  build:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Instalación de dependencias
        run: npm ci

      - name: Compilar proyecto
        run: npm run build --if-present

      - name: Ejecutar tests específicos
        run: npm run test -- --watch=false --browsers=ChromeHeadless --include="**/(insignias|perfilusuario|auth)*.spec.ts"

  # ---------------------------------------------------
  # JOB 2: Deploy a Vercel (solo si tests pasan y rama es main o develop)
  # ---------------------------------------------------
  deploy:
    name: Deploy a Vercel
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'

    steps:
      - uses: actions/checkout@v4

      - name: Instalar Vercel CLI
        run: npm install -g vercel

      - name: Deploy a Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        run: |
          echo "Iniciando deploy a Vercel..."
          if [ "${GITHUB_REF##*/}" = "main" ]; then
            echo "Deploy de producción (main)"
            vercel --prod --token $VERCEL_TOKEN --confirm
          else
            echo "Deploy de preview (develop)"
            vercel --token $VERCEL_TOKEN --confirm
          fi
